USE [BTLon2]
GO

/****** Object:  Table [dbo].[SV_MonThi_KiThi]    Script Date: 11/23/2019 8:32:41 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SV_MonThi_KiThi](
	[UserID] [uniqueidentifier] NOT NULL,
	[KyThiID] [uniqueidentifier] NOT NULL,
	[MonThiID] [uniqueidentifier] NOT NULL,
	[IsValid] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[KyThiID] ASC,
	[MonThiID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SV_MonThi_KiThi]  WITH CHECK ADD  CONSTRAINT [FK_SV_MonThi_KiThi_KyThi] FOREIGN KEY([KyThiID])
REFERENCES [dbo].[KyThi] ([KyThiID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SV_MonThi_KiThi] CHECK CONSTRAINT [FK_SV_MonThi_KiThi_KyThi]
GO

ALTER TABLE [dbo].[SV_MonThi_KiThi]  WITH CHECK ADD  CONSTRAINT [FK_SV_MonThi_KiThi_MonThi] FOREIGN KEY([MonThiID])
REFERENCES [dbo].[MonThi] ([MonThiID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SV_MonThi_KiThi] CHECK CONSTRAINT [FK_SV_MonThi_KiThi_MonThi]
GO

ALTER TABLE [dbo].[SV_MonThi_KiThi]  WITH CHECK ADD  CONSTRAINT [FK_SV_MonThi_KiThi_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SV_MonThi_KiThi] CHECK CONSTRAINT [FK_SV_MonThi_KiThi_User]
GO

