USE [BTLon2]
GO

/****** Object:  Table [dbo].[KyThi]    Script Date: 11/23/2019 8:30:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KyThi](
	[KyThiID] [uniqueidentifier] NOT NULL,
	[KyThiIdFake] [nvarchar](50) NULL,
	[KyThiName] [nvarchar](50) NULL,
 CONSTRAINT [PK_KyThi] PRIMARY KEY CLUSTERED 
(
	[KyThiID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

