USE [BTLon2]
GO

/****** Object:  Table [dbo].[CaThi_MonThi]    Script Date: 11/23/2019 8:31:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CaThi_MonThi](
	[CaMtID] [uniqueidentifier] NOT NULL,
	[CaThiID] [uniqueidentifier] NOT NULL,
	[MonThiID] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_CaThi_MonThi] PRIMARY KEY CLUSTERED 
(
	[CaMtID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CaThi_MonThi]  WITH CHECK ADD  CONSTRAINT [FK_CaThi_MonThi_CaThi] FOREIGN KEY([CaThiID])
REFERENCES [dbo].[CaThi] ([CaThiID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CaThi_MonThi] CHECK CONSTRAINT [FK_CaThi_MonThi_CaThi]
GO

ALTER TABLE [dbo].[CaThi_MonThi]  WITH CHECK ADD  CONSTRAINT [FK_CaThi_MonThi_MonThi] FOREIGN KEY([MonThiID])
REFERENCES [dbo].[MonThi] ([MonThiID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CaThi_MonThi] CHECK CONSTRAINT [FK_CaThi_MonThi_MonThi]
GO

